#!/usr/bin/env python3
"""Generate beta-bridge CSV + LaTeX (Appendix C) and reverse-DCF sensitivity
heatmap (Figure 11) for the Zhipu AI (2513.HK) valuation paper.

Usage:
    python scripts/comps_beta_and_reverse_dcf.py

Outputs:
    data/comps_beta_bridge.csv
    eventstudy/reverse_dcf_sensitivity.csv
    figures/fig11_reverse_dcf_heatmap.png
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yfinance as yf

ROOT = Path(__file__).resolve().parents[1]
FIGURES = ROOT / "figures"
DATA = ROOT / "data"
EVENTSTUDY = ROOT / "eventstudy"

# ---- shared style (same palette as rebuild_outputs.py) ----
C_RED = "#B22222"
C_BLUE = "#1F4E79"
C_INK = "#222222"

# ============================================================
# PART 1 — Comparable-company beta bridge (yfinance → CSV + LaTeX)
# ============================================================

COMPS = {
    "Salesforce": "CRM",
    "Palantir": "PLTR",
    "Snowflake": "SNOW",
    "Datadog": "DDOG",
    "MongoDB": "MDB",
    "Cloudflare": "NET",
    "C3.ai": "AI",
}

TAX_RATE_BETA = 0.21  # US statutory rate for unlevering


def fetch_beta_bridge() -> pd.DataFrame:
    """Fetch levered beta, market cap, total debt from yfinance and unlever."""
    rows = []
    for name, ticker in COMPS.items():
        t = yf.Ticker(ticker)
        info = t.info or {}
        beta = info.get("beta", float("nan"))
        mcap = info.get("marketCap", float("nan"))
        debt = info.get("totalDebt", 0.0) or 0.0
        de = debt / mcap if (mcap and mcap > 0) else float("nan")
        bu = beta / (1 + (1 - TAX_RATE_BETA) * de) if (beta == beta) else float("nan")
        rows.append({"Company": name, "Ticker": ticker,
                      "Levered_beta": beta, "Mcap_USD": mcap,
                      "Total_debt_USD": debt, "Debt_Equity": de,
                      "Unlevered_beta": bu})
    df = pd.DataFrame(rows)
    median_bu = df["Unlevered_beta"].median()
    return df, median_bu


def write_beta_latex(df: pd.DataFrame, median_bu: float, path: Path) -> None:
    """Emit a LaTeX tabular ready for \\input{}."""
    rows_tex = []
    for _, r in df.iterrows():
        de_pct = f"{r['Debt_Equity']:.1f}\\%" if r["Debt_Equity"] == r["Debt_Equity"] else "n/a"
        rows_tex.append(
            f"{r['Company']} & {r['Levered_beta']:.2f} & {de_pct} & "
            f"{r['Unlevered_beta']:.2f} \\\\"
        )
    body = "\n".join(rows_tex)
    tex = (
        "% Auto-generated by scripts/comps_beta_and_reverse_dcf.py\n"
        "\\begin{table}[H]\n"
        "\\centering\n"
        "\\caption{Comparable-company beta bridge (data via \\texttt{yfinance}, "
        f"accessed {pd.Timestamp.now().strftime('%d~%B~%Y')}).}}\n"
        "\\label{tab:beta}\n"
        "\\begin{tabular}{lccc}\n"
        "\\toprule\n"
        "Comparable & Levered beta & Debt/equity & Unlevered beta \\\\\n"
        "\\midrule\n"
        f"{body}\n"
        "\\midrule\n"
        "\\textbf{Median} & --- & --- & "
        f"\\textbf{{{median_bu:.2f}}} \\\\\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n"
    )
    path.write_text(tex, encoding="utf-8")
    print(f"[OK] LaTeX table → {path}")


# ============================================================
# PART 2 — Reverse-DCF sensitivity (required 2035 revenue grid)
# ============================================================

# Fixed assumptions (match rebuild_outputs.py / main.tex)
WACC_BASE = 0.135
TERM_G = 0.04
TAX = 0.15
SALES_TO_CAP = 1.8
SHARES_M = 435
USD_HKD = 7.8
NET_CASH_USDM = 550
REV_2026_USDM = 200

# Grid
WACC_GRID = np.array([0.10, 0.115, 0.13, 0.135, 0.15, 0.17, 0.20])
MARGIN_GRID = np.array([0.20, 0.28, 0.35, 0.40, 0.50])

# Target equity value (market, 2026-06-26)
TARGET_EQUITY_USDM = 114_000  # ~US$114bn in millions
TARGET_EV_USDM = TARGET_EQUITY_USDM - NET_CASH_USDM  # ~US$113,450m


def growth_path(base_rev: float) -> list[float]:
    """Base-case revenue growth rates 2026→2035 (9 intervals)."""
    return [0.56, 0.50, 0.44, 0.38, 0.32, 0.26, 0.20, 0.14, 0.08]


def compute_required_2035_rev(wacc: float, term_margin: float) -> float:
    """Solve for 2035 revenue (US$m) that makes EV = TARGET_EV_USDM.

    We scale a unit-revenue path: assume $1 of 2035 revenue, compute the
    growth path backward, get unit FCFFs, discount them, then scale up to
    hit the target EV.
    """
    g_path = growth_path(1.0)
    # Build revenue path for $1 of 2035 revenue (work backward)
    revs = [1.0]
    for g in reversed(g_path):
        revs.insert(0, revs[0] / (1 + g))
    # revs[0] = 2026 rev implied by $1 of 2035 rev

    # Compute FCFF per unit of 2035 revenue
    # Margin ramps linearly from -30% (2026) to term_margin (2035)
    n = len(revs)  # 10 years
    margins = np.linspace(-0.30, term_margin, n)
    fcf_unit = []
    pv_unit = 0.0
    for i in range(n):
        yr = 2026 + i
        rev_i = revs[i]
        ebit_i = rev_i * margins[i]
        # Tax: zero when EBIT negative (NOL accumulation)
        tax_i = max(0, ebit_i * TAX)
        nopat_i = ebit_i - tax_i
        # Reinvestment via sales-to-capital
        if i == 0:
            reinvest_i = rev_i / SALES_TO_CAP
        else:
            reinvest_i = (rev_i - revs[i - 1]) / SALES_TO_CAP
        fcff_i = nopat_i - reinvest_i
        pv_unit += fcff_i / (1 + wacc) ** (i + 1)
        fcf_unit.append(fcff_i)

    # Terminal value at 2035 per unit of 2035 revenue
    fcff_term = fcf_unit[-1]
    if wacc <= TERM_G:
        return float("inf")  # undefined
    tv_unit = fcff_term * (1 + TERM_G) / (wacc - TERM_G)
    pv_tv_unit = tv_unit / (1 + wacc) ** n

    # Total EV per unit of 2035 revenue
    ev_per_unit = pv_unit + pv_tv_unit
    if ev_per_unit <= 0:
        return float("inf")

    # Required 2035 revenue = target EV / ev_per_unit
    # But we need to subtract PV of net cash path — actually EV = equity - net cash
    # We want: EV_unit * R_2035 = TARGET_EV
    req_rev = TARGET_EV_USDM / ev_per_unit
    return req_rev


def build_sensitivity_grid() -> pd.DataFrame:
    """Build the WACC × margin grid of required 2035 revenue (US$bn)."""
    rows = []
    for w in WACC_GRID:
        for m in MARGIN_GRID:
            rev = compute_required_2035_rev(w, m)
            rows.append({"WACC": w, "Term_margin": m, "Req_rev_2035_USDm": rev})
    df = pd.DataFrame(rows)
    df["Req_rev_2035_USDbn"] = df["Req_rev_2035_USDm"] / 1000
    return df


def plot_sensitivity_heatmap(df: pd.DataFrame, path: Path) -> None:
    """Heatmap: WACC (y) × terminal margin (x), colour = required 2035 rev (US$bn)."""
    pivot = df.pivot(index="WACC", columns="Term_margin", values="Req_rev_2035_USDbn")
    pivot = pivot.sort_index(ascending=True)  # low WACC at bottom

    data = pivot.values.astype(float)
    # Cap for visual clarity
    data_capped = np.clip(data, 0, 500)

    fig, ax = plt.subplots(figsize=(8, 5))
    im = ax.imshow(data_capped, cmap="YlOrRd", aspect="auto",
                   origin="lower", interpolation="nearest")

    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels([f"{c:.0%}" for c in pivot.columns], fontsize=10)
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels([f"{r:.1%}" for r in pivot.index], fontsize=10)
    ax.set_xlabel("Terminal operating margin", fontsize=11)
    ax.set_ylabel("WACC", fontsize=11)

    # Annotate cells with actual values
    for i in range(len(pivot.index)):
        for j in range(len(pivot.columns)):
            val = data[i, j]
            label = f"${val:.0f}B" if val < 1e6 else ">$1T"
            colour = "white" if val > 250 else C_INK
            ax.text(j, i, label, ha="center", va="center",
                    fontsize=9, fontweight="bold", color=colour)

    # Highlight the base-case cell (WACC=13.5%, margin=40%)
    base_i = list(pivot.index).index(0.135) if 0.135 in pivot.index else None
    base_j = list(pivot.columns).index(0.40) if 0.40 in pivot.columns else None
    if base_i is not None and base_j is not None:
        ax.add_patch(plt.Rectangle((base_j - 0.5, base_i - 0.5), 1, 1,
                                   fill=False, edgecolor=C_RED, linewidth=2.5))

    cbar = plt.colorbar(im, ax=ax, shrink=0.8)
    cbar.set_label("Required 2035 revenue (US$bn)", fontsize=10)

    ax.set_title(
        "Reverse-DCF sensitivity: 2035 revenue needed to justify US$114bn equity\n"
        "(red box = base-case WACC 13.5% / terminal margin 40%)",
        fontsize=12, fontweight="bold", pad=12,
    )
    plt.tight_layout()
    fig.savefig(path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"[OK] Heatmap → {path}")


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    DATA.mkdir(exist_ok=True)
    EVENTSTUDY.mkdir(exist_ok=True)
    FIGURES.mkdir(exist_ok=True)

    # ---- Part 1: Beta bridge ----
    print("[1/4] Fetching comparable-company data from yfinance …")
    df_beta, median_bu = fetch_beta_bridge()
    csv_beta = DATA / "comps_beta_bridge.csv"
    df_beta.to_csv(csv_beta, index=False)
    print(f"[OK] CSV → {csv_beta}")
    tex_beta = ROOT / "paper" / "beta_bridge_auto.tex"
    write_beta_latex(df_beta, median_bu, tex_beta)

    # ---- Part 2: Reverse-DCF sensitivity ----
    print("[2/4] Computing reverse-DCF sensitivity grid …")
    df_sens = build_sensitivity_grid()
    csv_sens = EVENTSTUDY / "reverse_dcf_sensitivity.csv"
    df_sens.to_csv(csv_sens, index=False)
    print(f"[OK] CSV → {csv_sens}")

    print("[3/4] Plotting sensitivity heatmap …")
    fig_path = FIGURES / "fig11_reverse_dcf_heatmap.png"
    plot_sensitivity_heatmap(df_sens, fig_path)

    # Print a quick summary for the paper
    base_rev = compute_required_2035_rev(WACC_BASE, 0.40)
    print(f"\n[Summary] Base case (WACC={WACC_BASE:.1%}, margin=40%): "
          f"required 2035 rev ≈ US${base_rev / 1000:.0f}B")
    for w in [0.10, 0.15, 0.20]:
        r = compute_required_2035_rev(w, 0.40)
        print(f"  WACC={w:.0%}, margin=40%: US${r / 1000:.0f}B")
    for m in [0.28, 0.35, 0.50]:
        r = compute_required_2035_rev(WACC_BASE, m)
        print(f"  WACC={WACC_BASE:.1%}, margin={m:.0%}: US${r / 1000:.0f}B")


if __name__ == "__main__":
    main()
